import { DM_Sans } from "next/font/google";
import "./globals.css"
import { Toaster } from "@/components/ui/sonner"
const dm_sans = DM_Sans({
    subsets:["latin"], weight:["400","500","100","200","300","600","700","800","900" ]
})
export const metadata = {
    title: "Tri State Community Services",
    description: "Generated by create next app",
};


export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body
            className={`${dm_sans.className} antialiased tracking-tight`}
        >
        <div className={`max-w-[1200px] w-full h-full m-8 text-[#001A6E] mx-auto select-none`}>
            {children}
        </div>
        <Toaster/>
        </body>
        </html>
    );
}